imports:
  commons: commons.yml
service:
  auth: false
  base-path: /alternatePaymentTypes
  endpoints:
    getAlternatePaymentType:
      path: /{guid}
      method: GET
      docs: |
        Returns an `AlternatePaymentType`
        object containing information about an alternative form of payment
        configured for a restaurant. Alternate payment types are forms
        of payment that are not standard in the Toast POS and that are
        configured for a particular restaurant. For example, a
        third-party service that processes payments might be configured
        as an alternate payment type.
      display-name: |
        Get an alternative payment type
      path-parameters:
        guid:
          docs: The Toast POS GUID of the alternative form of payment.
          type: string
      request:
        headers:
          Toast-Restaurant-External-ID:
            docs: |
              The Toast POS GUID of the restaurant that the alternate payment
              type is configured for.
            type: string
        name: |-
          alternative-payment-type
          -request
      response: AlternatePaymentType
    alternatePaymentTypesGet:
      path: ""
      method: GET
      docs: |
        Returns an array of `AlternatePaymentType`
        objects containing information about alternative forms of
        payment that are configured for a restaurant. Alternate
        payment types are forms of payment that are not standard in the
        Toast POS and that are configured for a particular restaurant.
        For example, a third-party service that processes payments
        might be configured as an alternate payment type. If a
        `lastModified` date is specified, returns all objects that were
        created or modified after that date.
      display-name: |
        Get alternative payment types
      request:
        query-parameters:
          pageToken:
            docs: >
              A string that identifies the set of data objects that the  endpoint will
              return in its response data. You can use this  parameter to
              retrieve one page of response data. You  get the value that you
              supply in the `pageToken` parameter  from the
              `Toast-Next-Page-Token` header field value of a  previous request
              to the endpoint. For more information, see  <a
              href="https://doc.toasttab.com/doc/devguide/apiResponseDataPagination.html">Paginating
              response data</a>.
            type: optional<string>
          pageSize:
            docs: >
              The number of objects to return in the array. Deprecated. For more
              information, see  <a
              href="https://doc.toasttab.com/doc/devguide/apiResponseDataPagination.html">Paginating
              response data</a>.
            type: optional<integer>
          page:
            docs: >
              The sequence number of the first object to return in the array.
              Deprecated. For more information, see  <a
              href="https://doc.toasttab.com/doc/devguide/apiResponseDataPagination.html">Paginating
              response data</a>.
            type: optional<integer>
          lastModified:
            docs: |
              Limits the return data to objects created or modified after
              a specific date and time. For example:
              `2015-12-01T00:00:00.000+0000`.
            type: optional<string>
        headers:
          Toast-Restaurant-External-ID:
            docs: |
              The Toast POS GUID of the restaurant that the configuration
              applies to.
            type: string
        name: |-
          alternative-payment-types
          -request
      response: list<AlternatePaymentType>
types:
  AlternatePaymentType:
    extends:
      - commons.ExternalReference
      - AlternatePaymentType_allOf
  AlternatePaymentType_allOf:
    properties:
      name:
        docs: The name of the alternate payment type.
        type: optional<string>
