imports:
  commons: commons.yml
service:
  auth: false
  base-path: /menuGroups
  endpoints:
    getMenuGroup:
      path: /{guid}
      method: GET
      docs: |
        Returns a `MenuGroup`
        object containing information about a section within a menu.
      display-name: |
        Get a menu group
      path-parameters:
        guid:
          docs: The Toast POS GUID of the menu group.
          type: string
      request:
        headers:
          Toast-Restaurant-External-ID:
            docs: |
              The Toast POS GUID of the restaurant that the configuration
              applies to.
            type: string
        name: |-
          a-menu-group
          -request
      response: MenuGroup
    getAllMenuGroups:
      path: ""
      method: GET
      docs: |
        Returns an array of `MenuGroup` objects
        containing information about the subsections of the menus
        configured for a restaurant. If a `lastModified` date is
        specified, returns all objects that were created or modified
        after that date.
      display-name: |
        Get menu groups
      request:
        query-parameters:
          pageToken:
            docs: >
              A string that identifies the set of data objects that the  endpoint will
              return in its response data. You can use this  parameter to
              retrieve one page of response data. You  get the value that you
              supply in the `pageToken` parameter  from the
              `Toast-Next-Page-Token` header field value of a  previous request
              to the endpoint. For more information, see  <a
              href="https://doc.toasttab.com/doc/devguide/apiResponseDataPagination.html">Paginating
              response data</a>.
            type: optional<string>
          pageSize:
            docs: >
              The number of objects to return in the array. Deprecated. For more
              information, see  <a
              href="https://doc.toasttab.com/doc/devguide/apiResponseDataPagination.html">Paginating
              response data</a>.
            type: optional<integer>
          page:
            docs: >
              The sequence number of the first object to return in the array.
              Deprecated. For more information, see  <a
              href="https://doc.toasttab.com/doc/devguide/apiResponseDataPagination.html">Paginating
              response data</a>.
            type: optional<integer>
          lastModified:
            docs: |
              Limits the return data to objects created or modified after
              a specific date and time. For example:
              `2015-12-01T00:00:00.000+0000`.
            type: optional<string>
        headers:
          Toast-Restaurant-External-ID:
            docs: |
              The Toast POS GUID of the restaurant that the configuration
              applies to.
            type: string
        name: |-
          menu-groups
          -request
      response: list<MenuGroup>
types:
  MenuGroup:
    extends:
      - commons.ExternalReference
      - MenuGroup_allOf
  MenuGroup_allOf:
    properties:
      name:
        docs: The name of the menu group as it appears in the Toast POS.
        type: optional<string>
      menu: optional<commons.ExternalReference>
      orderableOnline:
        docs: >
          Deprecated. Indicates whether restaurant guests can order from the menu
          online. Toast is streamlining and improving the set of configuration
          options that restaurants use for configuring whether a menu entity can
          be ordered online. As part of this change, the `orderableOnline` value
          has been deprecated. Before 2020-05-25, you should transition to using
          the `visibility` array that the menus API returns for each menu
          entity, instead of this `orderableOnline` value, to determine if the
          entity should be available for online ordering. See <a
          href="https://doc.toasttab.com/doc/devguide/apiDeprecatedApiFunctions.html#apiMenuEntityVisibilityEnhancements">Menu
          entity visibility enhancements (rolled out)</a> for more information.
        type: optional<string>
      visibility:
        docs: >
          Deprecated. Indicates where the menu is displayed and who can see it. *
          ALL: Visible to everyone (servers and customers) * POS_ONLY: Only
          visible to servers * NONE: Hidden from everyone Toast is streamlining
          and improving the set of configuration options that restaurants use
          for configuring where a menu entity is visible (for example, on a
          Toast POS device or on a restaurant's Toast online ordering website).
          As part of this change, the `visibility` value in the configuration
          API has been deprecated. Before 2020-05-25, you should transition to
          using the `visibility` array that the menus API returns for each menu
          entity, instead of this `visibility` value, to determine where the
          entity should be visible. See <a
          href="https://doc.toasttab.com/doc/devguide/apiDeprecatedApiFunctions.html#apiMenuEntityVisibilityEnhancements">Menu
          entity visibility enhancements (rolled out)</a> for more information.
        type: optional<commons.MenuDisplay>
      parent: optional<commons.ExternalReference>
      items:
        docs: |
          An array of `ExternalReference` objects containing the
          identifiers of the `MenuItem`s in the menu
          group.
        type: optional<list<commons.ExternalReference>>
      subgroups:
        docs: |
          An array of `ExternalReference` objects containing the
          identifiers of the child `MenuGroup`s in
          the menu group. Empty if the menu group does not include any child
          menu groups.
        type: optional<list<commons.ExternalReference>>
      optionGroups:
        docs: |
          An array of `ExternalReference` objects containing the
          identifiers of the child `MenuOptionGroup`s
          that contain modifiers applicable to the group, its
          subgroups and its items. Does not include
          `MenuOptionGroup`s inherited from its parent `MenuGroup`.
        type: optional<list<commons.ExternalReference>>
      inheritOptionGroups:
        docs: |
          True if this `MenuGroup` inherits `MenuOptionGroup`s
          from its parent `MenuGroup`.
        type: optional<boolean>
      images:
        docs: |
          An array of `Image`
          objects associated with with the `MenuGroup`.
        type: optional<list<commons.Image>>
      unitOfMeasure:
        docs: >
          The unit of measure used to determine the price of items in this group.
          This value is not relevant if `inheritUnitOfMeasure` is true.
        type: optional<commons.PriceUnit>
      inheritUnitOfMeasure:
        docs: |
          True if this `MenuGroup` inherits its unit of measure
          from its parent `MenuGroup` or (if its parent is null)
          its parent `Menu`.
        type: optional<boolean>

