imports:
  commons: commons.yml
service:
  auth: false
  base-path: /preModifierGroups
  endpoints:
    preModifierGroupsGuidGet:
      path: /{guid}
      method: GET
      docs: |
        Returns a `PreModifierGroup` object
        containing information about a pre modifier group.
      display-name: |
        Get a pre-modifier group
      path-parameters:
        guid:
          docs: The Toast POS GUID of the pre-modifier.
          type: string
      request:
        headers:
          Toast-Restaurant-External-ID:
            docs: |
              The Toast POS GUID of the restaurant that the configuration
              applies to.
            type: string
        name: |-
          pre-modifier-group
          -request
      response: PreModifierGroup
    preModifierGroupsGet:
      path: ""
      method: GET
      docs: |
        Returns an array of `PreModifierGroup` objects
        containing information about PreModifierGroup configured
        for a restaurant.
      display-name: |
        Get pre modifier groups
      request:
        query-parameters:
          pageToken:
            docs: >
              A string that identifies the set of data objects that the  endpoint will
              return in its response data. You can use this  parameter to
              retrieve one page of response data. You  get the value that you
              supply in the `pageToken` parameter  from the
              `Toast-Next-Page-Token` header field value of a  previous request
              to the endpoint. For more information, see  <a
              href="https://doc.toasttab.com/doc/devguide/apiResponseDataPagination.html">Paginating
              response data</a>.
            type: optional<string>
          pageSize:
            docs: >
              The number of objects to return in the array. Deprecated. For more
              information, see  <a
              href="https://doc.toasttab.com/doc/devguide/apiResponseDataPagination.html">Paginating
              response data</a>.
            type: optional<integer>
          page:
            docs: >
              The sequence number of the first object to return in the array.
              Deprecated. For more information, see  <a
              href="https://doc.toasttab.com/doc/devguide/apiResponseDataPagination.html">Paginating
              response data</a>.
            type: optional<integer>
          lastModified:
            docs: |
              Limits the return data to objects created or modified after
              a specific date and time. For example:
              `2015-12-01T00:00:00.000+0000`.
            type: optional<string>
        headers:
          Toast-Restaurant-External-ID:
            docs: |
              The Toast POS GUID of the restaurant that the configuration
              applies to.
            type: string
        name: |-
          pre-modifier-groups
          -request
      response: list<PreModifierGroup>
types:
  PreModifierGroup:
    extends:
      - commons.ToastReference
      - PreModifierGroup_allOf
  PreModifierGroup_allOf:
    properties:
      name:
        docs: The name of the pre modifier that appears in the Toast POS.
        type: optional<string>
      isDefault:
        docs: |
          True if this PreModifierGroup is set as the default Group.
          Only a single PreModifierGroup can be set as default at one time.
        type: optional<boolean>
