imports:
  commons: commons.yml
service:
  auth: false
  base-path: /voidReasons
  endpoints:
    voidReasonsGuidGet:
      path: /{guid}
      method: GET
      docs: |
        Returns a `VoidReason` object
        containing information about a cause for making a sale invalid
        configured for a restaurant.
      display-name: |
        Get a void sale reason
      path-parameters:
        guid:
          docs: The Toast POS GUID of the void reason.
          type: string
      request:
        headers:
          Toast-Restaurant-External-ID:
            docs: |
              The Toast POS GUID of the restaurant that the configuration
              applies to.
            type: string
        name: |-
          void-sale-reason
          -request
      response: VoidReason
    voidReasonsGet:
      path: ""
      method: GET
      docs: |
        Returns an array of `VoidReason` objects
        containing information about causes for making a sale invalid
        configured for a restaurant. If a `lastModified` date is
        specified, returns all objects that were created or modified
        after that date.
      display-name: |
        Get void sale reasons
      request:
        query-parameters:
          pageToken:
            docs: >
              A string that identifies the set of data objects that the  endpoint will
              return in its response data. You can use this  parameter to
              retrieve one page of response data. You  get the value that you
              supply in the `pageToken` parameter  from the
              `Toast-Next-Page-Token` header field value of a  previous request
              to the endpoint. For more information, see  <a
              href="https://doc.toasttab.com/doc/devguide/apiResponseDataPagination.html">Paginating
              response data</a>.
            type: optional<string>
          pageSize:
            docs: >
              The number of objects to return in the array. Deprecated. For more
              information, see  <a
              href="https://doc.toasttab.com/doc/devguide/apiResponseDataPagination.html">Paginating
              response data</a>.
            type: optional<integer>
          page:
            docs: >
              The sequence number of the first object to return in the array.
              Deprecated. For more information, see  <a
              href="https://doc.toasttab.com/doc/devguide/apiResponseDataPagination.html">Paginating
              response data</a>.
            type: optional<integer>
          lastModified:
            docs: |
              Limits the return data to objects created or modified after
              a specific date and time. For example:
              `2015-12-01T00:00:00.000+0000`.
            type: optional<string>
        headers:
          Toast-Restaurant-External-ID:
            docs: |
              The Toast POS GUID of the restaurant that the configuration
              applies to.
            type: string
        name: |-
          void-sale-reasons
          -request
      response: list<VoidReason>
types:
  VoidReason:
    extends:
      - commons.ToastReference
      - VoidReason_allOf
  VoidReason_allOf:
    docs: When voiding something through the POS, the user must choose a
      preconfigured void reason.
    properties:
      name:
        docs: The name of this void reason.
        type: optional<string>
