imports:
  commons: commons.yml
service:
  auth: false
  base-path: /noSaleReasons
  endpoints:
    get:
      path: /{guid}
      method: GET
      docs: |
        Returns a `NoSaleReason` object
        containing information about a no sale reason.
      display-name: |
        Get a no sale reason
      path-parameters:
        guid:
          docs: The Toast POS GUID of the no sale reason.
          type: string
      request:
        headers:
          Toast-Restaurant-External-ID:
            docs: |
              The Toast POS GUID of the restaurant that the configuration
              applies to.
            type: string
        name: |-
          a-no-sale-reason
          -request
      response: NoSaleReason
    getAll:
      path: ""
      method: GET
      docs: |
        Returns an array of `NoSaleReason` objects
        containing information about no sale reasons configured
        for a restaurant.
      display-name: |
        Get no sale reasons
      request:
        query-parameters:
          pageToken:
            docs: >
              A string that identifies the set of data objects that the  endpoint will
              return in its response data. You can use this  parameter to
              retrieve one page of response data. You  get the value that you
              supply in the `pageToken` parameter  from the
              `Toast-Next-Page-Token` header field value of a  previous request
              to the endpoint. For more information, see  <a
              href="https://doc.toasttab.com/doc/devguide/apiResponseDataPagination.html">Paginating
              response data</a>.
            type: optional<string>
          pageSize:
            docs: >
              The number of objects to return in the array. Deprecated. For more
              information, see  <a
              href="https://doc.toasttab.com/doc/devguide/apiResponseDataPagination.html">Paginating
              response data</a>.
            type: optional<integer>
          page:
            docs: >
              The sequence number of the first object to return in the array.
              Deprecated. For more information, see  <a
              href="https://doc.toasttab.com/doc/devguide/apiResponseDataPagination.html">Paginating
              response data</a>.
            type: optional<integer>
          lastModified:
            docs: |
              Limits the return data to objects created or modified after
              a specific date and time. For example:
              `2015-12-01T00:00:00.000+0000`.
            type: optional<string>
        headers:
          Toast-Restaurant-External-ID:
            docs: |
              The Toast POS GUID of the restaurant that the configuration
              applies to.
            type: string
        name: |-
          no-sale-reasons
          -request
      response: list<NoSaleReason>
types:
  NoSaleReason:
    extends:
      - commons.ToastReference
    properties:
      name:
        docs: The name of the no sale reason that appears in the Toast POS.
        type: optional<string>
