imports:
  commons: commons.yml
service:
  auth: true
  base-path: /revenueCenters
  endpoints:
    get:
      path: /{guid}
      method: GET
      docs: |
        Returns a `RevenueCenter` object
        containing information about a segment of restaurant income,
        for reporting.
      display-name: |
        Get a revenue center
      path-parameters:
        guid:
          docs: The Toast POS GUID of the revenue center.
          type: string
      request:
        headers:
          Toast-Restaurant-External-ID:
            docs: |
              The Toast POS GUID of the restaurant that the configuration
              applies to.
            type: string
        name: |-
          revenue-center
          -request
      response: RevenueCenter
    getAll:
      path: ""
      method: GET
      docs: |
        Returns an array of `RevenueCenter` objects
        containing information about segments of restaurant income, for
        reporting. If a `lastModified` date is specified, returns all
        objects that were created or modified after that date.
      display-name: |
        Get revenue centers
      request:
        query-parameters:
          pageToken:
            docs: >
              A string that identifies the set of data objects that the  endpoint will
              return in its response data. You can use this  parameter to
              retrieve one page of response data. You  get the value that you
              supply in the `pageToken` parameter  from the
              `Toast-Next-Page-Token` header field value of a  previous request
              to the endpoint. For more information, see  <a
              href="https://doc.toasttab.com/doc/devguide/apiResponseDataPagination.html">Paginating
              response data</a>.
            type: optional<string>
          pageSize:
            docs: >
              The number of objects to return in the array. Deprecated. For more
              information, see  <a
              href="https://doc.toasttab.com/doc/devguide/apiResponseDataPagination.html">Paginating
              response data</a>.
            type: optional<integer>
          page:
            docs: >
              The sequence number of the first object to return in the array.
              Deprecated. For more information, see  <a
              href="https://doc.toasttab.com/doc/devguide/apiResponseDataPagination.html">Paginating
              response data</a>.
            type: optional<integer>
          lastModified:
            docs: |
              Limits the return data to objects created or modified after
              a specific date and time. For example:
              `2015-12-01T00:00:00.000+0000`.
            type: optional<string>
        headers:
          Toast-Restaurant-External-ID:
            docs: |
              The Toast POS GUID of the restaurant that the configuration
              applies to.
            type: string
        name: |-
          revenue-centers
          -request
      response: list<RevenueCenter>
types:
  RevenueCenter:
    extends:
      - commons.ToastReference
    docs: A set of ServiceAreas and POS devices for which separate revenue reports
      can be generated. For instance, a restaurant with a bar might choose to
      define two RevenueCenters, one for the bar and one for the dining area.
    properties:
      name:
        docs: The name of this revenue center.
        type: optional<string>
      description:
        docs: The description of this revenue center.
        type: optional<string>
